name: Docker Image

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Show versions
        run: |
          docker version
          docker buildx version
        
      - name: Log in to the registry
        run: echo "${{ secrets.PUBLIC_DOCKER_REGISTRY_PASSWORD }}" | docker login --username "${{ vars.PUBLIC_DOCKER_REGISTRY_USERNAME }}" --password-stdin
      
      - name: Set up builder
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
      
      - name: Build and push the image
        run: |
          # Try to support all platforms supported by the base image.
          # Run `docker buildx imagetools inspect image-name` to see the supported platforms.
          TAG_LATEST="${{ vars.DOCKER_IMAGE_NAME }}:latest"
          TAG_COMMIT="${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}"
          docker buildx build --platform linux/amd64,linux/arm64 -t $TAG_LATEST -t $TAG_COMMIT --push .
